language: java
jdk:
- openjdk8
install: true
addons:
  sonarcloud:
    organization: xm-online
    token:
      secure: Ni04mVkGIWSeV2M0nRkVPievTS2KuzxTnGJB06usqKwJAHajR+ejIFwz1vA+CKA2jFdSMafvsAuPVEUhyVDGGrkq86Q3qVPWGsNv+Iob/WlB+9JhyFFkcqr8X1ljO0vDhsDalCY+s5ImAEKme/u5Fq5JMI8CalhsboEM0Q7LMCWiBIyX3GbGQts8PCrN6Tp+RNb2H2fTzo/bFeyWCYhaCstXqRU3+X7ilD/rDl6ziPRCyOFf703ryQiMHzyGfjNJc8IL+b0Sxw1GQX7Nepmk4sfTkPOcAxQzPjlcS8IbNnZFty5hI0VtC8BZCGWQ44tb46dq4gD9lbuzRgGfroNyYNnjuOvP6zwmv9Y5uFa0b4ZX7B/3cnyz7p1ZlerdmKE07XvlwuZEsqsyYmtm/nS0/SIxQqYEAek+bwANTjKJpHrjhmd/kskxfVcnTwVEAtu/n8IQx+0ub5WcgTSKTnTPknp+14/83zq34DNyUX5CfraLN71VizUpsLBeK4EfAyfG8HIIEm6aSJwfvUSm4F/0wCG6PujIXEz66UC0EvKQX59zoqG00PwE1DazOJqc823kBxKhuJLmcyh+0BuTyn4sZIVt+tkyqm1o0urAtqKxBmVC2MxhMovYhDsOhMTLi92mUKYgNRnID/+GygHBKKegH2IG8AfRayCTltlX0PxkKt8=
    branches:
    - master

script:
- set -e
- "./gradlew --no-daemon --refresh-dependencies clean test"
- "./gradlew -x test -Pprod --no-daemon bootWar"
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export DOCKER_REPO=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/^xm-online\//xmonline\//g')
- export IMAGE_BRANCH=$(echo -n $TRAVIS_BRANCH | sed -e 's/\//-/g')
- export PROJECT_VERSION="$IMAGE_BRANCH"
- if [ "$IMAGE_BRANCH" == "master" ] || [ "$IMAGE_BRANCH" = "LTS"* ]; 
  then 
      PROJECT_VERSION=$(./gradlew -q  getProjectVersion);
      export SONAR_PK=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/\//:/g');
      ./gradlew -x test --no-daemon sonarqube -Dsonar.projectKey="$SONAR_PK"
      -Dsonar.projectName="$SONAR_PK" -Dsonar.java.binaries="." -Dsonar.projectVersion="$IMAGE_BRANCH";
      TAGS="$PROJECT_VERSION $PROJECT_VERSION-$TRAVIS_BUILD_NUMBER $(echo $PROJECT_VERSION | awk -F '.' '{printf $1"."$2" "$1}') latest";
  else
      TAGS="$IMAGE_BRANCH $IMAGE_BRANCH-$TRAVIS_BUILD_NUMBER";
  fi
- docker build -t app-docker-img --label commit_id="$TRAVIS_COMMIT" --label version="$PROJECT_VERSION" --label build_number="$TRAVIS_BUILD_NUMBER" --label build_url="$TRAVIS_BUILD_WEB_URL" --label git_url="$TRAVIS_REPO_SLUG" --label commit_message="$TRAVIS_COMMIT_MESSAGE" -f src/main/docker/Dockerfile .
- for TAG in $TAGS;
  do
      docker tag app-docker-img $DOCKER_REPO:$TAG;
      docker push $DOCKER_REPO:$TAG;
  done
cache:
  directories:
  - "~/.gradle"
  - "~/.m2"
env:
  global:
  - secure: pDGprx+3LF3XIdPnIMw/fC9nM43i22I4bfkGM2H3dZzin0mJSEBbkobXYW8n9KP0d8pFRQ4iorO5JmxT7bnEXX+i0iMK61NblWeA+jtFbfJXTkzKGl/NX9xALV3K7OPbb477tibLOeC0QtXmEJNtWRuPFbUigt8AXxzbeG35dqs0iIcLvc1x/OfXpKI4YUc5jdgRpGSSjUBbPPxi6YBZTCBsxqPZ1/1D+gKyWKrmnW6ew+FDfED21ZL8KjRrKfOjJS5F5Qycr0cWb1Rh9YcQg1jbnVg8Mq2G0lRk3lzz+0DaSdF1Al09ljDfoUFPK1q11lm4EgsCKtq85+PL+z+7XhBPfRuO1bHQaN604/nFoI0dJHxO8oNXIQMSfdMa36jRarr3Hho7FIVTO96JH5rF9cJ5u5ksMZxaBQS4MAyKN8v0LBBDhEDC7PhlNC20E8/qx0OWxlgpHEfTT7D/gNZmxs1KB66jqe0Twj5VCfApMioB9ZN6Cf5fvKqC9ypqdKM+XMVLIjHCrakfKmotPOu2MH2oL1DStrmlGY1BRCKW5TWfsTFgMVI8yrx3Z5UbigQ7/i+9WMeb0CHQ2JWhrMxVd7T8/fzqaiFDlag9Tpe+AIpHXfzMfigWCJ3JAa0BgpKJhObS77if0Ni5dm7mRYGRA23t1iUp3o1QaE2aTJFgLRg=
  - secure: VPpD/0FSMPO2AWNeFVjOYP7XFy4E/oD7pwIujyX8NTJpn10p3AMkRClD7EdQLryPre16NokzYjG+CtPHPZ2dOd9zrBqdk504p8vlb218Ri5ofzHB4GpNNvZsRnr0HUZQjVUFCtVlaF/QCLkzb3VCwO1wqExTN9PcXiHjcv5B4gBzrta3bR55SPIMG6guolo+SR1D55Yhoz9WUh+TG2EPE6H3wJShAF3WK0Q0Y8IZpdDzT8hJy4WZQRVfYCm3NIPV4ZPdnCSkz0pscksT165pLYT0wj4RPakN5Wd1+zcMEZcsEwP4nPQ6VzNTmddZnEg+kwjROKnQ+onFaRZ5H7yoPITjRBnHYVYFgYybBhKn8tOVr4uOgr9oK4ZcKzmdKTw9/zbXT4z+FREK8o6fxMvoSYMeeOQXSh0TpHc5Nf6IOofHuHTjDKbZ1RpMykefw3HNAnSA3hvAS5awi0P3T5SjiAqfW1gvZq9wBfhVEaTF+7bwRUFNfL/x9Nf1gU7jdNSPXBHawX/CQNO3YTfyd2HjLjqdlXmAalF0yvA8zMTtuBtATCTwhgwDUV4LhfBn7rSyhRSrssw/lpeV5BqJueytGQc1pJ8GulpNguy/aaSEMLt3kRUP2Mj0tG0gejWzNNFQu6rLwjW1in5HKNT9S+1vKI23JlIyDBh66mRBbiZows8=
notifications:
  slack:
    rooms:
      secure: O9Y3B0YsnZVzJnYqWpfOguToXfrAjg1sWw9sXEvcR3ICmevmkQZ7nWgNILwlsvbjnk4y2cKE/L46G9rgSTaJfbZhAMbC8z+01a5C9JmaRJyytFsUQCrhRBZE741MBmXhbyo9/aTZSXHjAYF0Yz4Lj2lk3QfqQ34QX7a97WjWApGucYnssgrQrB0r7X5M/dTy/5aBMfMaYtrjMrcj/ktY5mlZWIxprAoe/62uiaUxLrLMeEA0inDrA93IjILCDy0Hd9dgBSnVegwtvMHBf6teowj8HAzMMAXX5zfPfxdqes87VJ19dz6NbWc38Sm6L33iB5qzoLCGSsKh9m5zaPrcBG9K3iDWQQC90cRehV8y7USSt9FTw/uckUsZyRt5oOJohCIlNjtLWKm2GrYjKdiEr64VQLNihJXEHovHK+OG1y0hUG5ZQf3fX9D5Zsrq8yHJQjz0d4tH2KM37CaJ+TaEkqcC+u24jblSWah01BguBJrF62jBj4TR/4FwTT/sEgKdU6gVd7Vge9d+RPi/Wv27PQ7EjuhBsGPax4ySb2/mLN9O+2Y1ZIx/aZoBESfGufE/gTOLU7g02OkBZZbpp205FYEHE8ocDNJJzEOihDlKqQgIUu6qJvY/wIreFOufjULu3bpdJa1wmvqD1yd1rK5IWluqKpSBjRojOOWuXt9lRgM=
